baseURL: https://athecoder.com
languageCode: en-us
title: Arash
theme: "PaperMod"
params:
    GoogleAnalyticsID: "G-V05TN52E0Q"
    hideFooter: true
    ShowReadingTime: true
    homeInfoParams:
        Title: "Arash Arbabi"
        Content: |
          I am a software engineer. Hope to become an AI scientist soon.  

    socialIcons: # optional
        - name: "cv"
          url: "resume.pdf"
        - name: "stackoverflow"
          url: "https://stackoverflow.com/users/7116724/athecoder"
        - name: "linkedin"
          url: "https://www.linkedin.com/in/arash-arbabi-76603b177/"
        - name: "twitter"
          url: "https://twitter.com/ATheCoder"